security:
  oauth2:
    client:
        clientId: 1371573098test-477332204
        clientSecret: testdata
        accessTokenUri: http://127.0.0.1:9080/sso/oauth/token
        userAuthorizationUri: http://127.0.0.1:9080/sso/oauth/authorize
    resource:
      userInfoUri: http://127.0.0.1:9080/sso/user

apps:
  contentApiServer: http://127.0.0.1:8080/contentapi
  oauth2Server: http://127.0.0.1:9080/sso

info:
  app:
    name: gatewayapi
    description: Gateway API Rest Service

server:
  port: 8086
  contextPath: /gatewayapi
